name: Platform.Application CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: Platform-System/Platform.CI-CD/.github/workflows/dotnet-build-template.yml@main
    secrets: inherit
    with:
      project_path: 'Platform.Application.csproj'
      dependencies: 'Platform-System/Platform.Domain,Platform-System/Platform.SharedKernel'
